name: CD

on:
  pull_request:
    branches:
      - main
    types: closed

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  publish-docker-image:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    env:
      APP_NAME: "phx_liveview"
      MIX_ENV: "prod"
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Log in to Docker
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
      - name: Build and push Docker image
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: ./
          push: true
          tags: ${{ github.repository }}:latest
          build-args: |
            MIX_ENV=${{ env.MIX_ENV }}
            APP_NAME=${{ env.APP_NAME }}

  deploy:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    needs: publish-docker-image
    env:
      SSH_PRIVATE_KEY: ${{ secrets.AWS_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      WORK_DIR: ${{ secrets.WORK_DIR }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Get repo name
        run: |
          echo "${{github.repository}}" | cut -d "/" -f 2 > repo.txt
          echo "REPO_NAME=$(cat repo.txt)" >> $GITHUB_ENV
          rm -rf repo.txt
      - name: Set up SSH key
        run: |
          echo "${{ env.SSH_PRIVATE_KEY }}" | base64 -d > ~/aws.pem
          chmod 600 ~/aws.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ env.SSH_HOST }} > ~/.ssh/known_hosts
      - name: Deploy production
        run: |
          ssh -i ~/aws.pem -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.SSH_HOST }} "cd ${{ env.WORK_DIR }}/${{env.REPO_NAME}} && docker-compose pull && docker-compose up -d && docker image prune -f && exit"
      - name: Clean up
        run: rm -rf ~/aws.pem
